STATE_FILE_CORRUPTED = "state_file_corrupted"
STATE_NON_PUBKEY_MINT_DROPPED = "state_non_pubkey_mint_dropped"
EXIT_UNKNOWN_PENDING_RECONCILE = "exit_unknown_pending_reconcile"
EXIT_RECONCILED_CLOSED = "exit_reconciled_closed"
EXIT_RECONCILED_PARTIAL = "exit_reconciled_partial"
# Recovery invariant: tx confirmation alone is not settlement truth in Jupiter-only mode.
EXIT_TX_CONFIRMED_NEEDS_SETTLEMENT = "exit_tx_confirmed_needs_settlement"
# Position status when Jupiter/execution settlement is ambiguous (not a hard execution failure).
POSITION_RECONCILE_PENDING = "RECONCILE_PENDING"
# Execution returned a signature but executed token amounts could not be confirmed from primary+fallback chain.
SETTLEMENT_UNCONFIRMED = "settlement_unconfirmed"
JOURNAL_APPEND_FAILED = "journal_append_failed"
STATE_SAVE_FAILED = "state_save_failed"

REJECT_LOW_LIQUIDITY = "reject_low_liquidity"
REJECT_LOW_EXIT_LIQUIDITY = "reject_low_exit_liquidity"
REJECT_LOW_VOLUME = "reject_low_volume"
REJECT_BAD_BUY_SELL_RATIO = "reject_bad_buy_sell_ratio"
REJECT_MINTABLE = "reject_mintable"
REJECT_MINTABLE_MEMECOIN = "reject_mintable_memecoin"
REJECT_FREEZABLE = "reject_freezable"
REJECT_LOW_SCORE = "reject_low_score"
REJECT_NO_SELL_ROUTE = "reject_no_sell_route"
REJECT_HIGH_BUY_IMPACT = "reject_high_buy_impact"
REJECT_HIGH_SELL_IMPACT = "reject_high_sell_impact"
REJECT_TOKEN_TOO_OLD = "reject_token_too_old"
REJECT_CANDIDATE_BUILD_FAILED = "reject_candidate_build_failed"
REJECT_NO_BUY_ROUTE = "reject_no_buy_route"
REJECT_JUPITER_UNTRADABLE = "reject_jupiter_untradable"
REJECT_JUPITER_BAD_PROBE = "reject_jupiter_bad_probe"
REJECT_EXECUTION_ROUTE_MISSING = "reject_execution_route_missing"
REJECT_ECONOMIC_SANITY_FAILED = "reject_economic_sanity_failed"
REJECT_QUOTE_OUTPUT_TOO_LOW = "reject_quote_output_too_low"
REJECT_QUOTE_PRICE_IMPACT_INVALID = "reject_quote_price_impact_invalid"

EXEC_NO_ROUTE = "no_route"
EXEC_PROVIDER_UNAVAILABLE = "provider_unavailable"
EXEC_QUOTE_FAILED = "quote_failed"
EXEC_ORDER_FAILED = "order_failed"
EXEC_EXECUTE_FAILED = "execute_failed"
EXEC_EXECUTE_UNKNOWN = "execute_unknown"
EXEC_SKIPPED_DRY_RUN = "execute_skipped_dry_run"
EXEC_SKIPPED_LIVE_DISABLED = "execute_skipped_live_disabled"
EXEC_TX_BUILD_FAILED = "execute_tx_build_failed"
EXEC_TX_SIGN_FAILED = "execute_tx_sign_failed"
EXEC_TX_SEND_FAILED = "execute_tx_send_failed"
EXEC_V2_ORDER_BUILD_FAILED = "execute_v2_order_build_failed"
EXEC_V2_SIGN_FAILED = "execute_v2_sign_failed"
EXEC_V2_EXECUTE_FAILED = "execute_v2_execute_failed"
EXEC_SELL_PROCEEDS_UNAVAILABLE = "post_sell_proceeds_unavailable"
SELL_THRESHOLD_UNCOMPUTABLE = "sell_threshold_uncomputable"
EXEC_TX_CONFIRMED_FAILED = "tx_confirmed_failed"
EXEC_TX_CONFIRMED_SUCCESS = "tx_confirmed_success"

SAFETY_DAILY_LOSS_CAP = "safety_daily_loss_cap"
SAFETY_MAX_CONSEC_EXEC_FAILURES = "safety_max_consecutive_execution_failures"
SAFETY_STALE_MARKET_DATA = "safety_stale_market_data"
SAFETY_UNKNOWN_EXIT_SATURATION = "safety_unknown_exit_saturation"
SAFETY_MAX_EXIT_BLOCKED = "safety_max_exit_blocked_positions"

BIRDEYE_EXIT_LIQUIDITY_UNSUPPORTED_CHAIN = "birdeye_exit_liquidity_unsupported_chain"

# Terminal zombie: position has exhausted all retry attempts and cannot be sold.
# Operator must intervene manually. Position no longer consumes effective capacity.
POSITION_FINAL_ZOMBIE = "FINAL_ZOMBIE"
