STATE_FILE_CORRUPTED = "state_file_corrupted"
RECOVERY_QTY_REDUCED_TO_WALLET = "recovery_qty_reduced_to_wallet"
RECOVERY_WALLET_GT_STATE = "recovery_wallet_gt_state"
EXIT_UNKNOWN_PENDING_RECONCILE = "exit_unknown_pending_reconcile"
EXIT_RECONCILED_CLOSED = "exit_reconciled_closed"
EXIT_RECONCILED_PARTIAL = "exit_reconciled_partial"
JOURNAL_APPEND_FAILED = "journal_append_failed"
STATE_SAVE_FAILED = "state_save_failed"

REJECT_LOW_LIQUIDITY = "reject_low_liquidity"
REJECT_LOW_EXIT_LIQUIDITY = "reject_low_exit_liquidity"
REJECT_LOW_VOLUME = "reject_low_volume"
REJECT_BAD_BUY_SELL_RATIO = "reject_bad_buy_sell_ratio"
REJECT_MINTABLE = "reject_mintable"
REJECT_FREEZABLE = "reject_freezable"
REJECT_LOW_SCORE = "reject_low_score"
REJECT_NO_SELL_ROUTE = "reject_no_sell_route"
REJECT_HIGH_BUY_IMPACT = "reject_high_buy_impact"
REJECT_HIGH_SELL_IMPACT = "reject_high_sell_impact"
REJECT_TOKEN_TOO_OLD = "reject_token_too_old"
REJECT_CANDIDATE_BUILD_FAILED = "reject_candidate_build_failed"

EXEC_NO_ROUTE = "no_route"
EXEC_QUOTE_FAILED = "quote_failed"
EXEC_ORDER_FAILED = "order_failed"
EXEC_EXECUTE_FAILED = "execute_failed"
EXEC_EXECUTE_UNKNOWN = "execute_unknown"
EXEC_TX_CONFIRMED_FAILED = "tx_confirmed_failed"
EXEC_TX_CONFIRMED_SUCCESS = "tx_confirmed_success"

SAFETY_DAILY_LOSS_CAP = "safety_daily_loss_cap"
SAFETY_MAX_CONSEC_EXEC_FAILURES = "safety_max_consecutive_execution_failures"
SAFETY_STALE_MARKET_DATA = "safety_stale_market_data"
SAFETY_UNKNOWN_EXIT_SATURATION = "safety_unknown_exit_saturation"
SAFETY_MAX_EXIT_BLOCKED = "safety_max_exit_blocked_positions"
